modLoader = "javafml"
loaderVersion = "[50,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "dyed"
version = "${version}"
displayName = "Dyed"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Dyed"
issueTrackerURL = "https://github.com/yurisuika/Dyed/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Properly dyed horse armor!
'''

[[dependencies.dyed]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.dyed]]
modId = "forge"
mandatory = true
versionRange = "[50,)"
ordering = "NONE"
side = "CLIENT"