modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "dyed"
version = "${version}"
displayName = "Dyed"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Dyed"
issueTrackerURL = "https://github.com/yurisuika/Dyed/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Properly dyed horse armor!
'''

[[mixins]]
config = "dyed.mixins.json"

[[dependencies.dyed]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20.2,1.20.4]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.dyed]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[20.2,)"
ordering = "NONE"
side = "CLIENT"