modLoader = "javafml"
loaderVersion = "[37,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "dyed"
version = "${version}"
displayName = "Dyed"
displayURL = "https://github.com/yurisuika/Dyed"
issueTrackerURL = "https://github.com/yurisuika/Dyed/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Properly dyed horse armor!
'''

[[dependencies.dyed]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "AFTER"
side = "CLIENT"