modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "dyed"
version= " ${file.jarVersion}"
displayName = "Dyed"
displayURL = "https://github.com/yurisuika/Dyed"
issueTrackerURL = "https://github.com/yurisuika/Dyed/issues"
logoFile = "assets/dyed/icon.png"
authors = "yurisuika"
description = '''
Properly dyed horse armor!
'''

[[dependencies.dyed]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "AFTER"
side = "CLIENT"